# Generated by Django 2.2.4 on 2019-08-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20)),
                ('gender1', models.CharField(max_length=5)),
                ('gender2', models.CharField(max_length=5)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('waist', models.CharField(max_length=10)),
                ('disease1', models.CharField(max_length=5)),
                ('disease2', models.CharField(max_length=5)),
                ('disease3', models.CharField(max_length=5)),
                ('smoking1', models.CharField(max_length=5)),
                ('drinking1', models.CharField(max_length=5)),
            ],
        ),
    ]
